name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
          
      - name: Install cargo-llvm-cov and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest,cargo-tarpaulin,just

      - name: Cache conda packages
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0 # Increment to reset cache if needed
        with:
          path: ${{ env.HOME }}/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-json-fortran

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1
        with:
          auto-activate-base: true
          activate-environment: ""
          use-only-tar-bz2: true  # Important for caching
          
      - name: Install Conda dependencies
        shell: bash -l {0}
        run: conda install --channel conda-forge json-fortran
          
      - name: Generate conformance files
        shell: bash -l {0}
        run: just gen-conform
      
      - name: Cache setup
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          cache-on-failure: true
          key: ${{ hashFiles('**/Cargo.toml') }}

      - name: Gather coverage
        shell: bash
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov --no-report --doc
          mkdir coverage
          cargo llvm-cov report --doctests --lcov --output-path coverage/lcov.info

      # - name: ✨ Publish to CodeCov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: "coverage/lcov.info"
      #     disable_search: true
      #     fail_ci_if_error: true

      # - name: ✨ Publish to Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
